import type { Product } from './types';

// Seed product data — maps to generated images in /public/products
export const SEED_PRODUCTS: Omit<Product, 'id'>[] = [
  // ===== GOLD =====
  {
    name: 'Royal Temple Necklace',
    nameTa: 'ராஜ கோயில் நெக்லஸ்',
    slug: 'royal-temple-necklace',
    description:
      'Exquisite 22K gold temple necklace with intricate peacock motifs and antique finish. A timeless South Indian heritage piece.',
    descriptionTa:
      'மயில் வடிவங்களுடன் கூடிய 22K தங்க கோயில் நெக்லஸ். பாரம்பரிய அழகு.',
    category: 'Temple',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 32.5,
    makingCharge: 14500,
    price: 245000,
    oldPrice: 272000,
    image: '/products/gold-necklace-1.png',
    images: ['/products/gold-necklace-1.png', '/products/gold-pendant.png', '/products/gallery-3.png'],
    stock: 5,
    rating: 4.9,
    reviewCount: 128,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    isOffer: false,
    tags: ['Gold', 'Necklace', 'Temple', 'Bridal'],
  },
  {
    name: 'Bridal Haram Necklace',
    nameTa: 'மணமகள் ஹாரம்',
    slug: 'bridal-haram-necklace',
    description:
      'Stunning 22K gold long haram adorned with rubies and emeralds. The perfect centrepiece for a South Indian bride.',
    descriptionTa: 'மாணிக்கம் மற்றும் மரகதங்களுடன் கூடிய 22K தங்க நீண்ட ஹாரம்.',
    category: 'Bridal',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 48.2,
    makingCharge: 22000,
    price: 385000,
    oldPrice: 420000,
    image: '/products/gold-necklace-2.png',
    images: ['/products/gold-necklace-2.png', '/products/bridal-set.png'],
    stock: 3,
    rating: 5.0,
    reviewCount: 86,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    isOffer: true,
    tags: ['Gold', 'Necklace', 'Bridal', 'Wedding'],
  },
  {
    name: 'Filigree Gold Bangles',
    nameTa: 'பிலிகிரி தங்க வளையல்கள்',
    slug: 'filigree-gold-bangles',
    description: 'Set of ornate 22K gold bangles with delicate filigree work. Stack them for a regal look.',
    descriptionTa: 'நுணுக்கமான பிலிகிரி வேலைப்பாடுடன் கூடிய 22K தங்க வளையல் செட்.',
    category: 'Bangles',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 18.6,
    makingCharge: 8500,
    price: 152000,
    image: '/products/gold-bangles.png',
    images: ['/products/gold-bangles.png'],
    stock: 8,
    rating: 4.8,
    reviewCount: 64,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    isOffer: false,
    tags: ['Gold', 'Bangles'],
  },
  {
    name: 'Solitaire Gold Ring',
    nameTa: 'சாலிடயர் தங்க மோதிரம்',
    slug: 'solitaire-gold-ring',
    description: 'Brilliant solitaire diamond set on a 22K gold band. An eternal symbol of love.',
    descriptionTa: '22K தங்கத்தில் ஒளிரும் வைர மோதிரம்.',
    category: 'Rings',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 4.2,
    makingCharge: 4200,
    price: 68500,
    oldPrice: 75000,
    image: '/products/gold-ring-diamond.png',
    images: ['/products/gold-ring-diamond.png', '/products/diamond-ring.png'],
    stock: 12,
    rating: 4.9,
    reviewCount: 210,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    isOffer: true,
    tags: ['Gold', 'Rings', 'Diamond'],
  },
  {
    name: 'Pearl Jhumka Earrings',
    nameTa: 'முத்து ஜும்கா காதணிகள்',
    slug: 'pearl-jhumka-earrings',
    description: 'Traditional 22K gold jhumka earrings with elegant pearl drops. Handcrafted perfection.',
    descriptionTa: 'முத்து தொங்கல்களுடன் கூடிய பாரம்பரிய 22K தங்க ஜும்கா.',
    category: 'Earrings',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 8.4,
    makingCharge: 3800,
    price: 54200,
    image: '/products/gold-earrings.png',
    images: ['/products/gold-earrings.png'],
    stock: 15,
    rating: 4.7,
    reviewCount: 95,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    isOffer: false,
    tags: ['Gold', 'Earrings'],
  },
  {
    name: 'Deity Gold Pendant',
    nameTa: 'தெய்வ தங்க பெண்டன்ட்',
    slug: 'deity-gold-pendant',
    description: 'Sacred 22K gold pendant with intricate deity design. Perfect for daily wear and auspicious occasions.',
    descriptionTa: 'தெய்வ வடிவமைப்புடன் கூடிய 22K தங்க பெண்டன்ட்.',
    category: 'Pendants',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 6.1,
    makingCharge: 2800,
    price: 39800,
    image: '/products/gold-pendant.png',
    images: ['/products/gold-pendant.png'],
    stock: 20,
    rating: 4.8,
    reviewCount: 42,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    isOffer: false,
    tags: ['Gold', 'Pendants'],
  },
  {
    name: 'Diamond Gold Bracelet',
    nameTa: 'வைர தங்க வளையல்',
    slug: 'diamond-gold-bracelet',
    description: 'Elegant 22K gold bracelet with subtle diamond accents. Modern luxury for everyday elegance.',
    descriptionTa: 'வைர அலங்காரத்துடன் கூடிய 22K தங்க வளையல்.',
    category: 'Bracelets',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 12.3,
    makingCharge: 6200,
    price: 98500,
    oldPrice: 110000,
    image: '/products/gold-bracelet.png',
    images: ['/products/gold-bracelet.png'],
    stock: 7,
    rating: 4.9,
    reviewCount: 58,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    isOffer: true,
    tags: ['Gold', 'Bracelets', 'Diamond'],
  },
  {
    name: 'Mangalsutra Gold',
    nameTa: 'மாங்கல்யம்',
    slug: 'mangalsutra-gold',
    description: 'Traditional gold mangalsutra with black beads and an ornate gold pendant.',
    descriptionTa: 'கருப்பு மணிகளுடன் கூடிய பாரம்பரிய தங்க மாங்கல்யம்.',
    category: 'Mangalsutra',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 14.8,
    makingCharge: 5400,
    price: 112000,
    image: '/products/gallery-4.png',
    images: ['/products/gallery-4.png'],
    stock: 9,
    rating: 4.8,
    reviewCount: 73,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    isOffer: false,
    tags: ['Gold', 'Mangalsutra', 'Wedding'],
  },
  // ===== SILVER =====
  {
    name: 'Minimalist Silver Necklace',
    nameTa: 'மினிமலிஸ்ட் வெள்ளி நெக்லஸ்',
    slug: 'minimalist-silver-necklace',
    description: 'Elegant 925 sterling silver necklace with a modern minimalist pendant. Everyday sophistication.',
    descriptionTa: 'நவீன வடிவமைப்புடன் கூடிய 925 வெள்ளி நெக்லஸ்.',
    category: 'Necklace',
    material: 'Silver',
    purity: '925 Sterling',
    weight: 12.5,
    makingCharge: 850,
    price: 4200,
    oldPrice: 5200,
    image: '/products/silver-necklace.png',
    images: ['/products/silver-necklace.png'],
    stock: 25,
    rating: 4.6,
    reviewCount: 156,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    isOffer: true,
    tags: ['Silver', 'Necklace'],
  },
  {
    name: 'Engraved Silver Bangles',
    nameTa: 'வெள்ளி வளையல்கள்',
    slug: 'engraved-silver-bangles',
    description: 'Set of polished sterling silver bangles with subtle traditional engraving.',
    descriptionTa: 'பாரம்பரிய செதுக்கு வேலைப்பாடுடன் கூடிய வெள்ளி வளையல்கள்.',
    category: 'Bangles',
    material: 'Silver',
    purity: '925 Sterling',
    weight: 32.4,
    makingCharge: 1450,
    price: 6800,
    image: '/products/silver-bangles.png',
    images: ['/products/silver-bangles.png'],
    stock: 18,
    rating: 4.7,
    reviewCount: 88,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    isOffer: false,
    tags: ['Silver', 'Bangles'],
  },
  {
    name: 'Topaz Silver Ring',
    nameTa: 'டோபாஸ் வெள்ளி மோதிரம்',
    slug: 'topaz-silver-ring',
    description: 'Elegant sterling silver ring with a sparkling blue topaz stone. Modern chic design.',
    descriptionTa: 'நீல டோபாஸ் கல்லுடன் கூடிய வெள்ளி மோதிரம்.',
    category: 'Rings',
    material: 'Silver',
    purity: '925 Sterling',
    weight: 5.2,
    makingCharge: 450,
    price: 2800,
    oldPrice: 3500,
    image: '/products/silver-ring.png',
    images: ['/products/silver-ring.png'],
    stock: 30,
    rating: 4.5,
    reviewCount: 64,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    isOffer: true,
    tags: ['Silver', 'Rings'],
  },
  // ===== ROSE GOLD =====
  {
    name: 'Heart Rose Gold Necklace',
    nameTa: 'ஹார்ட் ரோஸ் கோல்ட் நெக்லஸ்',
    slug: 'heart-rose-gold-necklace',
    description: 'Delicate rose gold necklace with a heart pendant and shimmering diamonds. Modern romance.',
    descriptionTa: 'இதய வடிவ பெண்டன்டுடன் கூடிய ரோஸ் கோல்ட் நெக்லஸ்.',
    category: 'Necklace',
    material: 'Rose Gold',
    purity: '18K Rose Gold',
    weight: 6.8,
    makingCharge: 3200,
    price: 48500,
    oldPrice: 55000,
    image: '/products/rosegold-necklace.png',
    images: ['/products/rosegold-necklace.png'],
    stock: 11,
    rating: 4.9,
    reviewCount: 134,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    isOffer: true,
    tags: ['Rose Gold', 'Necklace', 'Diamond'],
  },
  {
    name: 'Pink Diamond Rose Gold Ring',
    nameTa: 'பிங்க் வைர ரோஸ் கோல்ட் மோதிரம்',
    slug: 'pink-diamond-rose-gold-ring',
    description: 'Elegant rose gold solitaire ring with a stunning pink diamond. A modern classic.',
    descriptionTa: 'பிங்க் வைரத்துடன் கூடிய ரோஸ் கோல்ட் சாலிடயர் மோதிரம்.',
    category: 'Rings',
    material: 'Rose Gold',
    purity: '18K Rose Gold',
    weight: 3.6,
    makingCharge: 3800,
    price: 78500,
    image: '/products/rosegold-ring.png',
    images: ['/products/rosegold-ring.png'],
    stock: 6,
    rating: 5.0,
    reviewCount: 47,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    isOffer: false,
    tags: ['Rose Gold', 'Rings', 'Diamond'],
  },
  {
    name: 'Morganite Rose Gold Earrings',
    nameTa: 'மோர்கனைட் ரோஸ் கோல்ட் காதணிகள்',
    slug: 'morganite-rose-gold-earrings',
    description: 'Elegant rose gold stud earrings with soft morganite stones. Everyday luxury.',
    descriptionTa: 'மோர்கனைட் கற்களுடன் கூடிய ரோஸ் கோல்ட் காதணிகள்.',
    category: 'Earrings',
    material: 'Rose Gold',
    purity: '18K Rose Gold',
    weight: 4.1,
    makingCharge: 2100,
    price: 32500,
    image: '/products/rosegold-earrings.png',
    images: ['/products/rosegold-earrings.png'],
    stock: 14,
    rating: 4.7,
    reviewCount: 52,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    isOffer: false,
    tags: ['Rose Gold', 'Earrings'],
  },
  // ===== DIAMOND =====
  {
    name: 'Brilliant Diamond Necklace',
    nameTa: 'பிரகாச வைர நெக்லஸ்',
    slug: 'brilliant-diamond-necklace',
    description: 'Luxury diamond necklace set in white gold. Brilliant cut diamonds for an unforgettable sparkle.',
    descriptionTa: 'வெள்ளை தங்கத்தில் ஒளிரும் வைர நெக்லஸ் செட்.',
    category: 'Necklace',
    material: 'Diamond',
    purity: 'VS1 / White Gold',
    weight: 9.5,
    makingCharge: 18500,
    price: 245000,
    oldPrice: 280000,
    image: '/products/diamond-necklace.png',
    images: ['/products/diamond-necklace.png'],
    stock: 4,
    rating: 5.0,
    reviewCount: 39,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    isOffer: true,
    tags: ['Diamond', 'Necklace', 'Bridal'],
  },
  {
    name: 'Halo Platinum Diamond Ring',
    nameTa: 'ஹாலோ பிளாட்டினம் வைர மோதிரம்',
    slug: 'halo-platinum-diamond-ring',
    description: 'Stunning halo setting with brilliant diamonds on a platinum band. The ultimate proposal ring.',
    descriptionTa: 'பிளாட்டினத்தில் ஹாலோ வைர மோதிரம்.',
    category: 'Rings',
    material: 'Diamond',
    purity: 'Platinum / VS1',
    weight: 5.8,
    makingCharge: 12000,
    price: 185000,
    image: '/products/diamond-ring.png',
    images: ['/products/diamond-ring.png'],
    stock: 5,
    rating: 4.9,
    reviewCount: 67,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    isOffer: false,
    tags: ['Diamond', 'Rings', 'Platinum'],
  },
  // ===== WEDDING / BRIDAL =====
  {
    name: 'Complete Bridal Set',
    nameTa: 'முழு மணமகள் செட்',
    slug: 'complete-bridal-set',
    description:
      'Complete South Indian bridal set — 22K gold necklace with matching earrings and maang tikka, adorned with rubies and emeralds.',
    descriptionTa: 'மாணிக்கம், மரகதம் கலந்த முழு திருமண நகை செட்.',
    category: 'Wedding',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 85.4,
    makingCharge: 45000,
    price: 685000,
    oldPrice: 750000,
    image: '/products/bridal-set.png',
    images: ['/products/bridal-set.png', '/products/gold-necklace-2.png', '/products/gallery-2.png'],
    stock: 2,
    rating: 5.0,
    reviewCount: 28,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    isOffer: true,
    tags: ['Gold', 'Bridal', 'Wedding', 'Set'],
  },
  {
    name: 'Antique Temple Necklace',
    nameTa: 'பழமையான கோயில் நெக்லஸ்',
    slug: 'antique-temple-necklace',
    description: 'Traditional South Indian temple jewellery necklace with goddess motif and antique finish.',
    descriptionTa: 'தெய்வ வடிவமைப்புடன் கூடிய பாரம்பரிய கோயில் நகை.',
    category: 'Temple',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 42.5,
    makingCharge: 19500,
    price: 345000,
    image: '/products/temple-necklace.png',
    images: ['/products/temple-necklace.png'],
    stock: 4,
    rating: 4.9,
    reviewCount: 54,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    isOffer: false,
    tags: ['Gold', 'Temple', 'Heritage'],
  },
  // ===== MEN / KIDS / COINS =====
  {
    name: 'Royal Men\'s Gold Chain',
    nameTa: 'ஆண்கள் தங்க செயின்',
    slug: 'royal-mens-gold-chain',
    description: 'Heavy 22K gold chain necklace for men with a bold thick-link design.',
    descriptionTa: 'கனமான 22K தங்க செயின் — ஆண்களுக்கான ராஜ வடிவம்.',
    category: 'Men',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 28.6,
    makingCharge: 13500,
    price: 228000,
    oldPrice: 250000,
    image: '/products/mens-chain.png',
    images: ['/products/mens-chain.png'],
    stock: 6,
    rating: 4.8,
    reviewCount: 41,
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
    isOffer: true,
    tags: ['Gold', 'Men', 'Chain'],
  },
  {
    name: 'Kids Gold Anklet Set',
    nameTa: 'குழந்தைகள் தங்க கால் சங்கிலி',
    slug: 'kids-gold-anklet-set',
    description: 'Delicate 22K gold anklet and bangle set for kids. Perfect for special occasions.',
    descriptionTa: 'குழந்தைகளுக்கான 22K தங்க கால் சங்கிலி மற்றும் வளையல் செட்.',
    category: 'Kids',
    material: 'Gold',
    purity: '916 Hallmark (22K)',
    weight: 8.2,
    makingCharge: 3200,
    price: 52800,
    image: '/products/kids-jewellery.png',
    images: ['/products/kids-jewellery.png'],
    stock: 10,
    rating: 4.9,
    reviewCount: 36,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    isOffer: false,
    tags: ['Gold', 'Kids'],
  },
  {
    name: 'Lakshmi Gold Coin 10g',
    nameTa: 'லட்சுமி தங்க நாணயம் 10g',
    slug: 'lakshmi-gold-coin-10g',
    description: 'Pure 24K gold coin with intricate Lakshmi goddess engraving. Perfect for gifting and investment.',
    descriptionTa: 'லட்சுமி தேவி வடிவமைப்புடன் கூடிய 24K தூய தங்க நாணயம்.',
    category: 'Gift',
    material: 'Gold',
    purity: '999 (24K)',
    weight: 10,
    makingCharge: 800,
    price: 74250,
    image: '/products/gold-coin.png',
    images: ['/products/gold-coin.png'],
    stock: 50,
    rating: 5.0,
    reviewCount: 215,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    isOffer: true,
    tags: ['Gold', 'Coin', 'Gift'],
  },
  {
    name: 'Silver Goddess Coin 50g',
    nameTa: 'வெள்ளி தேவி நாணயம் 50g',
    slug: 'silver-goddess-coin-50g',
    description: 'Pure silver coin with intricate goddess engraving. Auspicious and ideal for gifting.',
    descriptionTa: 'தேவி வடிவமைப்புடன் கூடிய தூய வெள்ளி நாணயம்.',
    category: 'Gift',
    material: 'Silver',
    purity: '999 Fine Silver',
    weight: 50,
    makingCharge: 600,
    price: 4725,
    oldPrice: 5500,
    image: '/products/silver-coin.png',
    images: ['/products/silver-coin.png'],
    stock: 40,
    rating: 4.8,
    reviewCount: 98,
    isFeatured: false,
    isNew: true,
    isBestSeller: true,
    isOffer: true,
    tags: ['Silver', 'Coin', 'Gift'],
  },
];

// Reviews start empty — admin adds real reviews based on actual customer purchases.
// No fake/seeded reviews.
export const REVIEWS_SEED: any[] = [];

